apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: demo9 
  janus-idp.io/tekton: demo9
  backstage.io/kubernetes-id: demo9
  backstage.io/kubernetes-namespace: ssm-app9 
  app.kubernetes.io/part-of: demo9
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml