apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: demo9
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: tssc-quay-quay-tssc-quay.apps.cluster-tn5tv.tn5tv.sandbox790.opentlc.com/tssc/ssm-demo9:0e8c60fe0f6f0ca819ba98f8fa4033f9a22e9a81@sha256:96c967a41ef9ff9682d6123a550e76b5e521488dee0085db13a8320719922043
          name: container-image
